name: Build and Push Umi-OCR Image

on:
  workflow_dispatch:

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Dockerfile
        run: |
          curl -o Dockerfile https://raw.githubusercontent.com/hiroi-sora/Umi-OCR_runtime_linux/main/Dockerfile

      - name: Verify Dockerfile
        run: test -f Dockerfile || (echo "Dockerfile missing"; exit 1)

      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/umi-ocr-paddle:latest
            ghcr.io/${{ github.repository_owner }}/umi-ocr-paddle:${{ github.run_id }}